import request from '@/utils/request'

export const getUserInfo = () => request({ url: '/api/user/getinfo', method: 'get' })
export const logout = () => request({ url: '/api/user/loginout', method: 'get' })
export const getUsers = params => request({ url: '/api/user/list', method: 'get', params })
export const createUser = data => request({ url: '/api/user', method: 'post', data })
export const updateUser = (id, data) => request({ url: `/api/user/${id}`, method: 'put', data })
export const setUserEnable = (id, enable) => request({ url: `/api/user/${id}/enable`, method: 'put', data: { enable } })
export const setUserAuthority = (id, authorityId) => request({ url: `/api/user/${id}/set_auth`, method: 'put', data: { authorityId } })
export const deleteUser = id => request({ url: `/api/user/${id}/delete_user`, method: 'delete' })
export const resetPassword = (id, newPassword) => request({ url: `/api/user/${id}/reset_pwd`, method: 'put', data: { new_pwd: newPassword } })
export const changePassword = (id, data) => request({ url: `/api/user/${id}/change_pwd`, method: 'post', data })

export const getAuthorities = params => request({ url: '/api/authority/getAuthorityList', method: 'get', params })
export const createAuthority = data => request({ url: '/api/authority', method: 'post', data })
export const updateAuthority = (id, data) => request({ url: `/api/authority/${id}`, method: 'put', data })
export const deleteAuthority = id => request({ url: `/api/authority/${id}`, method: 'delete' })
export const getBaseMenus = () => request({ url: '/api/menu/getBaseMenuTree', method: 'get' })
export const getAuthorityMenus = (id, params) => request({ url: `/api/menu/${id}/getMenuByAuthID`, method: 'get', params })
export const getDirectAuthorityMenus = id => getAuthorityMenus(id, { scope: 'direct' })
export const saveAuthorityMenus = (authorityId, menus) => request({ url: '/api/menu/add_menu_authority', method: 'post', data: { authorityId, menus } })
export const getApis = params => request({ url: '/api/sysApi/getAPiList', method: 'get', params })
export const getAuthorityPolicies = authorityId => request({ url: '/api/authority/getPolicyPathByAuthorityId', method: 'get', params: { authorityId } })
export const saveAuthorityPolicies = (authorityId, casbinInfos) => request({ url: '/api/authority/updateCasbinByAuthority', method: 'post', data: { authorityId, casbinInfos } })
